export const FETCH_CRYPTOCOMPARE_REQUEST = 'FETCH_CRYPTOCOMPARE_REQUEST';
export const FETCH_CRYPTOCOMPARE_SUCCESS = 'FETCH_CRYPTOCOMPARE_SUCCESS';
export const FETCH_CRYPTOCOMPARE_FAILURE = 'FETCH_CRYPTOCOMPARE_FAILURE';

export const FETCH_24_CURRENCY_REQUEST = 'FETCH_24_CURRENCY_REQUEST';
export const FETCH_24_CURRENCY_SUCCESS = 'FETCH_24_CURRENCY_SUCCESS';
export const FETCH_24_CURRENCY_FAILURE = 'FETCH_24_CURRENCY_FAILURE';

export const ORDER_CURRENCIES = 'ORDER_CURRENCIES';
