export const FETCH_1H_CURRENCY_REQUEST = 'FETCH_1H_CURRENCY_REQUEST';
export const FETCH_1H_CURRENCY_SUCCESS = 'FETCH_1H_CURRENCY_SUCCESS';
export const FETCH_1H_CURRENCY_FAILURE = 'FETCH_1H_CURRENCY_FAILURE';
export const FETCH_1H_CURRENCY_GET_CACHED = 'FETCH_1H_CURRENCY_GET_CACHED';

export const FETCH_24H_CURRENCY_REQUEST = 'FETCH_24H_CURRENCY_REQUEST';
export const FETCH_24H_CURRENCY_SUCCESS = 'FETCH_24H_CURRENCY_SUCCESS';
export const FETCH_24H_CURRENCY_FAILURE = 'FETCH_24H_CURRENCY_FAILURE';
export const FETCH_24H_CURRENCY_GET_CACHED = 'FETCH_24H_CURRENCY_GET_CACHED';

export const FETCH_7D_CURRENCY_REQUEST = 'FETCH_7D_CURRENCY_REQUEST';
export const FETCH_7D_CURRENCY_SUCCESS = 'FETCH_7D_CURRENCY_SUCCESS';
export const FETCH_7D_CURRENCY_FAILURE = 'FETCH_7D_CURRENCY_FAILURE';
export const FETCH_7D_CURRENCY_GET_CACHED = 'FETCH_7D_CURRENCY_GET_CACHED';

export const FETCH_30D_CURRENCY_REQUEST = 'FETCH_30D_CURRENCY_REQUEST';
export const FETCH_30D_CURRENCY_SUCCESS = 'FETCH_30D_CURRENCY_SUCCESS';
export const FETCH_30D_CURRENCY_FAILURE = 'FETCH_30D_CURRENCY_FAILURE';
export const FETCH_30D_CURRENCY_GET_CACHED = 'FETCH_30D_CURRENCY_GET_CACHED';

export const REFRESH_CURRENCY = 'REFRESH_CURRENCY';

export const ORDER_CURRENCIES = 'ORDER_CURRENCIES';
