export const FETCH_24_CURRENCY_REQUEST = 'FETCH_24_CURRENCY_REQUEST';
export const FETCH_24_CURRENCY_SUCCESS = 'FETCH_24_CURRENCY_SUCCESS';
export const FETCH_24_CURRENCY_FAILURE = 'FETCH_24_CURRENCY_FAILURE';

export const FETCH_24_CURRENCY_GET_CACHE = 'FETCH_24_CURRENCY_GET_CACHE';
export const FETCH_24_CURRENCY_TRY = 'FETCH_24_CURRENCY_TRY';

export const ORDER_CURRENCIES = 'ORDER_CURRENCIES';
